/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc20Sol from "./IERC20.sol";
export type { ierc20Sol };
export type { IOrder } from "./IOrder";
export type { Order } from "./Order";
